language: objective-c
osx_image: xcode7.3

notifications:
  slack: swiftgg:GTctPDWV5h8pPzaagds051WS
  email: false

before_install:
  - gem install cocoapods --pre

before_script:
  - carthage bootstrap

script:
  - xctool -workspace GGQ.xcworkspace -scheme GGQ-Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
